### ISSUE TITLE
A question - trying to understand your example

### ISSUE THREAD

**Issue by badphart** [jonashaag/prometheus-multiprocessing-example#1]
Hi Jonas

Thanks for posting your example but I hope you can help me to understand something.

In your example, I presume that yourapp is a flask application but the gunicorn application is serving the prometheus metics and your gunicorn start line specifies the WSGI app class.  So, when you start gunicorn is that what starts your flask app?  

My app starts with command line parameters (I guess I can change that) and it is a multi-processing daemon but it is not a WSGI callable.  Am I missing something?

You hello route is a nice greeting but your metrics route is doing some other stuff that appears Prometheus related.  Is the metrics route just to show what can be done or is it something functional for reporting prometheus metrics?  Or is the flask part providing the gunicorn content and the hello route is just there to show how you do other stuff?  What if the other stuff we need to do is not a web app?

**Comment by badphart** [comment]
I think I understand now but I wouldn't mind any corrections you want to make:

Flask isn't serving anything - it is servicing the request and is like the classic handler method.  So, something like how handler is to http server, flask is to gunicorn. (with perhaps some WSGI smarts wrapped around it)

I expect that I'd need to configure prometheus to scrape from myhoist:myport/metrics (didn't know you can do that) or maybe just not have the hello under the route '/' and have metrics under that route instead of '/metrics'.

Still not sure how I'd start my app since I think that it will need to be running under gunicorn.  Maybe I can just have code at the bottom of myapp to read instantiation values from somewhere and start the daemon processes.  (I'll have to explore that)

**Comment by jonashaag** [comment]
Hi @badphart, the questions you're asking show you should make yourself familiar with the basics of WSGI and Prometheus. Flask is a framework, not a server, so you need gunicorn to actually serve the application.
